---
- name: working with special cases
  hosts: all
  serial: 3
  vars_files:
    - credential1.yml
  tasks:
    - name: executing my technospreds.py script
      script: ./technospreds.py
      ignore_errors: true

    - name: printing my required output
      command: echo "this is technospreds devops class room training"
    
    - name: working on specialcases delegate_to option
      command: hostname -i
      delegate_to: server2

    - name: working on specialcases delegate_to option
      command: uname -a

    - name: working on specialcase ansible-valut
      command: echo "here is your database credential this is username {{dbusername}} and this is my database password {{dbpassword}} here is your databse used {{dbname}}"




    
